title: Bots VS Manusia
logo: /assets/img/bot.jpg
description: Bot semakin lama semakin pintar tiap detiknya, masih bisakah kita menang esok?
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
